# Generated by Django 4.1.5 on 2023-01-31 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('order_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_quantity', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('mobile_no', models.BigIntegerField()),
                ('c_add', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('seller_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=10)),
                ('seller_email_id', models.EmailField(max_length=50)),
                ('seller_mobile_no', models.BigIntegerField()),
                ('seller_add', models.TextField(max_length=100)),
                ('GST_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pr_name', models.CharField(max_length=200)),
                ('pr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pr_price', models.FloatField(default=1, max_length=20)),
                ('pr_status', models.BooleanField(default=1)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('description', models.TextField()),
                ('pr_image', models.ImageField(upload_to='product_img')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seller')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('pay_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay_type', models.CharField(max_length=20)),
                ('order_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.PositiveIntegerField(default=1, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('c_id', 'pr_id')},
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_quantity', models.PositiveIntegerField(default=1, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(related_name='product', through='app.orders', to='app.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('pr_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.product')),
                ('order_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
            ],
            options={
                'unique_together': {('pr_id', 'order_no')},
            },
        ),
    ]
