# Generated by Django 4.1.5 on 2023-01-31 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='pr_id',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='warehouse',
        ),
    ]
