# Generated by Django 4.1.4 on 2023-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_orders_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
