# Generated by Django 4.1.4 on 2023-01-23 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_cart_order_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('user', 'pr_id', 'c_id')},
        ),
    ]
