# Generated by Django 4.1.5 on 2023-01-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_name',
            field=models.CharField(max_length=200),
        ),
    ]
