# Generated by Django 4.1.5 on 2023-01-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_pr_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='ware_pr_quantity',
        ),
    ]
