# Generated by Django 4.1.5 on 2023-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
