# Generated by Django 4.1.5 on 2023-01-28 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_orders_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='c_id',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='pr_id',
            new_name='Product',
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('user', 'Product', 'Customer')},
        ),
    ]
