# Generated by Django 4.1.5 on 2023-01-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.cart'),
        ),
    ]
