# Generated by Django 4.1.5 on 2023-01-31 06:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_orders_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Customer',
            new_name='Custom',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='c_id',
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('user', 'Product', 'Custom', 'order_no')},
        ),
    ]
