# Generated by Django 4.1.5 on 2023-01-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_customer_orders_custom_remove_customer_c_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set(),
        ),
    ]
